### ISSUE TITLE
Add `help/{command}` endpoint

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/server-api#144]
Suggested by Marc DiPasquale in Slack comment https://asyncapi.slack.com/archives/CQVJXFNQL/p1662141074739369?thread_ts=1661395911.924239&cid=CQVJXFNQL

We should create such an endpoint `help/{command}` to return instruction of given command to the user. For example `help/generate` should return available parameters such an available templates etc. 

`help/{command}` is just a suggestion, we can go with other endpoint(s).

Also, what is very important, that endpoint should be done in a similar way as in our main CLI - https://github.com/asyncapi/cli#usage, so main `help` endpoint should return all available endpoints and particular one like `help/generate` should return details about given command.

cc @BOLT04 @smoya Do you want to add something, other requirements for task?

**Comment by BOLT04** [comment]
Hi @magicmatatjahu, I was a bit confused about what was the use case for this endpoint. By reading the thread on slack it makes sense to add the metadata info 👍, I've seen other APIs do that too (e.g. https://cloud.google.com/service-infrastructure/docs/service-metadata/reference/rest; https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_intro.html), although it might be a bit different... dunno 😅.

But I'm still confused about how we'll do it. Regarding naming, `meta` or `metadata` would be preferable to `help`, wdyt?
Since our goal is to provide additional information about our API resources, I think we could have the endpoints match their resource, so `generator` instead of `generate`.

I'd also like to ask if developers using this API, are most likely to go to each generator template's GitHub repository, and read the [docs for parameters](https://github.com/asyncapi/ts-nats-template#template-parameters), or call the metadata API with the template id (e.g. "@asyncapi/ts-nats-template")?
wdyt @magicmatatjahu @smoya ?

**Comment by tthijm** [comment]
Hi @magicmatatjahu @BOLT04, I would like to work on this.

**Comment by tthijm** [comment]
My approach is based on the fact that the `openapi.yaml` file is present, which contains all the neccessary information for solving this problem.

Firstly, one creates a `help.controller.ts` file in the `src/controllers` folder. In this file, a class `HelpController` which implements the `Controller` class should be exported as default. One may then, import this class in `server.ts`, and add an instance of this class to the controllers array for the `App` constructor.

The `HelpController` should implement the `Controller` class. It should therefore define a `basepath` property, and a `boot` method. This base path may be defined as `'/help'`. The `boot` method, may start with reading the `openapi.yaml` file, in order to fetch all available commands. Additionally, the method should initialise a router. This router, may only support two paths:

- basepath
  This should respond, with a list of all available commands.
- basepath/:command
  This should respond, with all the information regarding the particular command if it exists.

These routes can be implemented using Express' `Router.get()`.

As mentioned earlier, the `boot` method may start with reading the `openapi.yml` file, in order to fetch all available commands. One may start reading its content, using `fs.readFileSync()`, and save its result in a temporary variable. One is then able, to parse this content into readable YAML, by using AsyncAPI's parser, or any other parser supporting YAML. One may then has to create an interface matching the structure of this `openapi.yml`, in order to respect the TypeScript architecture.

To store the required command information, one may define two variables: `commands`, an object in which the command name is used as key, and the value is the corresponding information, and `shortCommands`, an object storing all the available commands, and a short summary of its purpose, in order to prevent having to iterate through `commands` to list all available commands.

One may now start actually reading the content of the `openapi.yml`, in order to extract the available commands. Since one has stored readable YAML earlier, one can iterate over this content. One may start with the `paths` field, which stores all the supported paths. Each key, of this field, stores the name of an available command, and its partial description. One can save this command name, as the key, and the partial description, as the value, and add this combination to the earlier defined `commands` object.

Additionally, one could map each tag, instead of being limited to only the command name, to the corresponding definition.

From openapi.yml:

```yaml
paths:
  /validate: # <- this, without '/', is the command name.
    ...
  /parse: ...
  /generate: ...
```

The just mentioned description is partial, since it is missing the request information, which includes the parameters a particular command expect, and its type. Since defined requests may contain `$ref`'s, one has to define these first. One may iterate over each mentioned `$ref` in the parsed YAML content, and save its type, as a value, in a temporary object named `types`. This will result in each `$ref` being mapped to an object defining it's type. This is neccessary for the next step.

One may now, iterate over every `components > schemas > {command_name}Request` field stored in the parsed YAML file. One can then extract the command name from each `{command_name}Request` key, and add the field's value, to the content saved in the `commands` object, using the extracted command name as key. If any value contains a ref, one can exchange this string, for the correct type, which will be present in the `types` object.

At this stage, `commands` should map each command name, to all the required corresponding information. However, `shortCommands` has not been defined yet. One may iterate through the `commands` object, and use each key as a key for the `shortCommands` object. Similary, particular fields of the value, to be used as the short definition describing the command, may be used as the value for the `shortCommands` object.

At this point, both `commands`, and `shortCommands` should be defined.

When a request to the base path is made, the response can consist of simply returning the `shortCommands` object, or formatting it in a particular way. On the other hand, when a request to basepath/:command is made, one simply has to check if the command is present in the `commands` object, and return the corresponding value, or inform the user that the command does not exist.

**Comment by BOLT04** [comment]
hi @tthijm, this issue is a part of the GSOC 2023 event, so it'll probably be picked up by students assigned to this project.
But you can look at other issues from this repo, or other AsyncAPI repos if you want to contribute 👍 .

**Comment by AayushSaini101** [comment]
@magicmatatjahu Can i work on this issue ?

**Comment by BOLT04** [comment]
hi @AayushSaini101 this was already implemented, but feel free to look at other issues 👍
